### ISSUE TITLE
Safari 12.1 - rendering glitch when inside a details element

### ISSUE THREAD

**Issue by davidef** [vaadin/vaadin-form-layout#111] opened 2019-05-23 09:56 UTC
In Safari Version 12.1 (14607.1.40.1.4), Vaadin 13.0.7
When inside a detail element there is a rendering glitch misplacing (or completely hiding in some cases) all the content

```
FormLayout content = new FormLayout();
content.add(new Button("b1"));
content.add(new Button("b2"));
Details detail = new Details("open", content);
add(detail);
```

![Screenshot 2019-05-23 at 11 50 35](https://user-images.githubusercontent.com/967588/58243478-0159dc00-7d51-11e9-864a-8fa48187ca9f.png)

We are currently using a workaround we found by adding this custom style
```
:host{
 opacity:0.99 !important
}
```

**Comment by web-padawan** [comment] 2019-05-23 09:59
Thanks for the issue and reproduction. We will work on the solution.
The root problem is most likely the same Safari bug which also caused #110

See also https://github.com/vaadin/vaadin-form-layout/issues/110#issuecomment-494241592

**Comment by web-padawan** [comment] 2019-05-28 10:16
Closing as duplicate of #110

**Closed by web-padawan** 2019-05-28 10:16 UTC

**Comment by martinisraelsen** [comment] 2019-05-28 11:55
> In Safari Version 12.1 (14607.1.40.1.4), Vaadin 13.0.7
> When inside a detail element there is a rendering glitch misplacing (or completely hiding in some cases) all the content
> 
> ```
> FormLayout content = new FormLayout();
> content.add(new Button("b1"));
> content.add(new Button("b2"));
> Details detail = new Details("open", content);
> add(detail);
> ```
> 
> ![Screenshot 2019-05-23 at 11 50 35](https://user-images.githubusercontent.com/967588/58243478-0159dc00-7d51-11e9-864a-8fa48187ca9f.png)
> 
> We are currently using a workaround we found by adding this custom style
> 
> ```
> :host{
>  opacity:0.99 !important
> }
> ```

Interesting. Where did you put the opacity? In the host element for the formlayout?

**Comment by davidef** [comment] 2019-05-28 16:13
> Interesting. Where did you put the opacity? In the host element for the formlayout?

Yes

```
<dom-module id="my-form-layout" theme-for="vaadin-form-layout">
  <template>
    <style>
      :host{
      	opacity: 0.99 !important;
      }
    </style>
  </template>
</dom-module>
```
