### ISSUE TITLE
Form layout is not responsive in V14

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/vaadin-form-layout#115] opened 2019-06-13 21:33 UTC
![ScreenFlow](https://user-images.githubusercontent.com/883698/59467881-9f3b4680-8de5-11e9-9b57-46e68e54da1a.gif)

The layout is the one generated by start.vaadin.com

Chrome 75, v14 beta 2

**Comment by Haprog** [comment] 2019-06-14 06:21
I can't reproduce the problem. `vaadin-form-layout` seems to work responsively as it should. I just downloaded the Form view example from start.vaadin.com. My machine was a bit sluggish when I recorded but the view and components seem to work as intended.
![form-layout-responsive](https://user-images.githubusercontent.com/75155/59487293-e4fb1c00-8e84-11e9-8191-737155d0611f.gif)
(This is on Chrome 75.0.3770.90 on macOS 10.14.5 with Vaadin 14.0.0.beta2 which runs `vaadin-form-layout` v2.1.2)

Closing as unable to reproduce.

**Closed by Haprog** 2019-06-14 06:21 UTC
