### ISSUE TITLE
vaadin-text-field, not native input should be used in examples by default

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-form-layout#27] opened 2017-05-02 06:53 UTC
Since our users (hopefully) will use vaadin components inside vaadin-form-layout, we should change examples to use `vaadin-text-field` as a default option. Currently, it's a native input and users missing examples with `vaadin-text-field`.

(This is the DX tests finding)

**Comment by platosha** [comment] 2017-05-02 10:23
Duplicate of #23?

**Closed** 2018-01-16 13:17 UTC
Labels: demos & docs
